<div class="panel panel-default">
    <div class="table-responsive">
        <table class="table table-admin">
            <thead>
            <tr>
                <th class="w60 text-center"><?= _text('Edit') ?></th>
                <th class="text-center w100"><?= _text('Domain') ?></th>
                <th class="text-center w100"><?= _text('Locale') ?></th>
                <th><?= _text('Value') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($items as $item): ?>
                <tr>
                    <td class="text-center">
                        <a data-cmd="toggle" data-target=":tr/form" role="button"><?= _text('edit') ?></a>
                    </td>
                    <td class="text-center w100"><?= $item->getDomainId() ?></td>
                    <td class="text-center"><?= $item->getLocaleId() ? $item->getLocaleId() : '<i>default</i>' ?></td>
                    <td>
                        <p class="text-danger"><?= $item->getMessageName() ?></p>
                        <p class="text-value"><?= $item->getMessageValue() ?></p>
                        <form method="post" class="form hide"
                              data-submit="admin.i18n.phrase.save"
                              action="<?= _url('admin.core.i18n.message', ['action' => 'save']) ?>">
                            <input type="hidden" name="domain_id"
                                   value="<?= $item->getDomainId() ?>"/>
                            <input type="hidden" name="message_name"
                                   value="<?= $item->getMessageName() ?>"/>
                            <input type="hidden" name="message_id"
                                   value="<?= $item->getId() ?>"/>
                            <div class="form-group">
                                <textarea class="form-control"
                                          name="message_value"><?= $item->getMessageValue() ?></textarea>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-sm btn-save"
                                        data-cmd="form.cmd"
                                        data-rel="save"
                                        type="button"><?= _text('Save Changes') ?>
                                </button>
                                <button type="button"
                                        data-cmd="form.confirm"
                                        data-rel="delete"
                                        class="btn btn-sm btn-danger"><?= _text('Delete') ?>
                                </button>
                                <button class="btn btn-sm btn-cancel"
                                        type="button" data-cmd="toggle"
                                        data-target=":tr/form"><?= _text('Cancel') ?>
                                </button>
                            </div>
                        </form>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<?php echo $items->render() ?>