<?php $defaultValue = \Phpfox::param('core.default_locale_id') ?>
<div class="panel panel-default">
    <div class="table-responsive">
        <table class="table table-admin">
            <thead>
            <tr>
                <th class="w40 text-center">#</th>
                <th>ID</th>
                <th><?= _text('English Name') ?></th>
                <th><?= _text('Native Name') ?></th>
                <th><?= _text('Code') ?></th>
                <th><?= _text('Direction') ?></th>
                <th><?= _text('Active') ?>?</th>
                <th><?= _text('Default') ?>?</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($items as $item): ?>
                <tr>
                    <td class="dropdown" data-cmd="dropdown">
                        <ul>
                            <li>
                                <a data-cmd="modal" href="<?= _url('admin.core.i18n.locale',
                                    ['action' => 'edit', 'locale_id' => $item->getId()]) ?>"><?= _text('Edit Settings') ?></a>
                            </li>
                            <li>
                                <a href="<?= _url('admin.core.i18n.locale',
                                    ['action' => 'default', 'locale_id' => $item->getId()]) ?>">
                                    <?= _text('Set Default Locale') ?>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a data-cmd="modal" href="<?= _url('admin.core.i18n.locale',
                                    ['action' => 'edit-currency-format', 'locale_id' => $item->getId()]) ?>"><?= _text('Number Format') ?></a>
                            </li>
                            <li>
                                <a data-cmd="modal" href="<?= _url('admin.core.i18n.locale',
                                    ['action' => 'edit-number-format', 'locale_id' => $item->getId()]) ?>"><?= _text('Currency Format') ?></a>
                            </li>
                        </ul>
                    </td>
                    <td><?= $item->getId() ?></td>
                    <td><?= $item->getName() ?></td>
                    <td><?= $item->getNativeName() ?></td>
                    <td><?= $item->getCode6391() ?></td>
                    <td><?= $item->getDirectionId() ?></td>
                    <td><?= _yesno($item->isActive(), true, true) ?></td>
                    <td><?= _yesno($item->isDefault(), true, false) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>