<div class="panel panel-default">
    <div class="table-responsive">
        <table class="table table-admin">
            <thead>
            <tr>
                <th class="text-center w40">#</th>
                <th>Title</th>
                <th class="w100">Driver</th>
                <th class="w50">Active</th>
                <th class="w50">Default</th>
                <th class="w50">Require</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($items as $item): ?>
                <tr>
                    <td class="dropdown" data-cmd="dropdown">
                        <ul>
                            <li><a href="<?= _url('admin.core.storage.adapter',
                                    ['action' => 'edit', 'adapter_id' => $item->getId()]) ?>">
                                    <?= _text('Edit') ?>
                                </a></li>
                            <li><a href="<?= _url('admin.core.storage.adapter',
                                    ['action' => 'delete', 'adapter_id' => $item->getId()]) ?>">
                                    <?= _text('Delete') ?>
                                </a></li>
                            <li><a href="<?= _url('admin.core.storage.adapter',
                                    ['action' => 'transfer', 'adapter_id' => $item->getId()]) ?>">
                                    <?= _text('Transfer') ?>
                                </a></li>
                        </ul>
                    </td>
                    <td><?= $item->getAdapterName() ?></td>
                    <td><?= $item->getDriverId() ?></td>
                    <td><?= _yesno($item->isActive()) ?></td>
                    <td><?= _yesno($item->isDefault()) ?></td>
                    <td><?= _yesno($item->isRequired(),true,false) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>