<!DOCTYPE html>
<html>
<head>
    <?= Phpfox::assets()->getStartHtml() ?>
</head>
<body class="admin-login">
<section>
    <div class="login">
        <form method="post">
            <h1>Admin</h1>
            <div class="form-group">
                <input type="text" name="username" class="form-control"
                       placeholder="Email address" autofocus required
                       maxlength="100"/>
            </div>
            <div class="form-group form-large">
                <input type="password" name="password" class="form-control"
                       placeholder="Password" required maxlength="32"/>
            </div>
            <button class="btn btn-danger btn-block" type="submit">Log In
            </button>
            <figure>
                <a class="btn btn-link" href="#">Go back</a>
            </figure>
        </form>
    </div>
</section>
<?= Phpfox::assets()->getShutdownHtml() ?>
</body>
</html>