<div class="layout-location-heading">
    <strong><?= _text($location['location_name'], '_core.layout') ?></strong>
    <span data-cmd="dropdown" role="button" style="float:right" data-target=":div/ul">
        <small><?= _text('edit') ?></small>
    </span>
    <ul class="hide" role="menu">
        <li role="menuitem">
            <a data-cmd="modal" href="<?= _url('admin.core.layout.block',
                [
                    'action'       => 'add',
                    'location_id'  => $location['location_id'],
                    'container_id' => $location['container_id'],
                ]) ?>"><?= _text('Add Block', '_core.layout') ?></a>
        </li>
        <li role="menuitem">
            <a role="button"><?= _text('Edit Settings', '_core.layout') ?></a>
        </li>
    </ul>
</div>
<ul class="layout-editor-location">
    <?php foreach ($blocks as $block): ?>
        <li class="layout-editor-block">
            <i class="fa fa-ellipsis-v" style="margin-left: -5px;font-size:smaller"></i>
            <?= $block['block_name'] ?>
            <span data-cmd="dropdown" role="button" style="float:right" data-target=":li/ul">
                <small>edit</small>
            </span>
            <div class="hide">
                <ul role="menu">
                    <li role="menuitem">
                        <a data-cmd="xhr" href="<?= _url('admin.core.layout.block',
                            ['action' => 'edit-block', 'block_id' => $block['block_id']]) ?>">Edit</a>
                    </li>
                    <li role="menuitem">
                        <a data-cmd="xhr" href="<?= _url('admin.core.layout.block',
                            ['action' => 'settings', 'block_id' => $block['block_id']]) ?>">Settings</a>
                    </li>
                    <li class="divider"></li>
                    <li role="menuitem">
                        <a data-cmd="xhr" href="<?= _url('admin.core.layout.block',
                            ['action' => 'enable', 'block_id' => $block['block_id']]) ?>">Enable</a>
                    </li>
                    <li role="menuitem">
                        <a data-cmd="xhr" href="<?= _url('admin.core.layout.block',
                            ['action' => 'disable', 'block_id' => $block['block_id']]) ?>">Disable</a>
                    </li>
                    <li class="divider"></li>
                    <li role="menuitem">
                        <a href="<?= _url('admin.core.layout.block', ['action' => 'delete', 'block_id' => $block['block_id']]) ?>">Remove</a>
                    </li>
                </ul>
            </div>
        </li>
    <?php endforeach; ?>
</ul>