<div class="panel panel-default">
    <div class="panel-heading">
        <div class="pull-right">
            <a role="link" data-cmd="modal" class="btn btn-xs btn-info" href="<?= _url('admin.core.layout.container',
                ['action' => 'edit', 'container_id' => $container->getName()]) ?>">Edit</a>
            <a role="link" data-cmd="modal" class="btn btn-xs btn-info" href="<?= _url('admin.core.layout.container',
                ['action' => 'delete', 'container_id' => $container->getName()]) ?>">Remove</a>
            <a role="link" data-cmd="modal" class="btn btn-xs btn-info" href="<?= _url('admin.core.layout.container',
                ['action' => 'toggle', 'container_id' => $container->getName()]) ?>">Toggle</a>
        </div>
        <div class="panel-title">Container #<?= $container->getName() ?> <sup><?= $container->getTypeId() ?></sup></div>
    </div>
    <?= $content ?>
</div>