<?php return [
    0 => 'id',
    1 => ['id' => 1,],
    2 => 'id',
    3 => [
        'id'           => 1,
        'is_app'       => 1,
        'is_theme'     => 1,
        'is_library'   => 1,
        'is_core'      => 1,
        'is_active'    => 1,
        'theme_id'     => 1,
        'is_language'  => 1,
        'priority'     => 1,
        'var_name'     => 1,
        'version'      => 1,
        'author'       => 1,
        'description'  => 1,
        'apps_icon'    => 1,
        'package_name' => 1,
        'path'         => 1,
        'package_type' => 1,
    ],
    4 => [],
];