<?php return [
    0 => null,
    1 => ['role_id' => 1,],
    2 => 'role_id',
    3 => [
        'role_id'       => 1,
        'inherit_id'    => 1,
        'title'         => 1,
        'is_special'    => 1,
        'prefix'        => 1,
        'suffix'        => 1,
        'icon_ext'      => 1,
        'is_super'      => 1,
        'is_admin'      => 1,
        'is_moderator'  => 1,
        'is_staff'      => 1,
        'is_registered' => 1,
        'is_banned'     => 1,
        'is_guest'      => 1,
    ],
    4 => [],
];