<?php return [
    0 => 'id',
    1 => ['id' => 1,],
    2 => 'id',
    3 => [
        'id'             => 1,
        'type_id'        => 1,
        'is_required'    => 1,
        'is_active'      => 1,
        'theme_id'       => 1,
        'priority'       => 1,
        'title'          => 1,
        'version'        => 1,
        'latest_version' => 1,
        'author'         => 1,
        'description'    => 1,
        'apps_icon'      => 1,
        'name'           => 1,
        'path'           => 1,
    ],
    4 => [],
];