<?php return [
    0 => 'id',
    1 => ['id' => 1,],
    2 => 'id',
    3 => [
        'id'          => 1,
        'ordering'    => 1,
        'menu_id'     => 1,
        'name'        => 1,
        'parent_name' => 1,
        'package_id'  => 1,
        'label'       => 1,
        'href'        => 1,
        'route'       => 1,
        'params'      => 1,
        'extra'       => 1,
        'permission'  => 1,
        'event'       => 1,
        'is_active'   => 1,
        'is_custom'   => 1,
        'item_type'   => 1,
        'is_ajax'     => 1,
        'is_self'     => 1,
    ],
    4 => [],
];