<div class="container">
    <div class="row">
        <h1>Themes</h1>
        <table class="table table-bordered table-responsive">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Version</th>
                <th>Author</th>
                <th>Active</th>
            </tr>
            <?php foreach ($items as $item): ?>
                <tr>
                    <td><?= $item['id'] ?></td>
                    <td><?= $item['var_name'] ?></td>
                    <td><?= $item['version'] ?></td>
                    <td><?= $item['author'] ?></td>
                    <td>
                        <label for="_">
                            <input name="item[active][]" id="_"
                                   type="checkbox" <?= $item['is_active']
                                ? 'checked' : '' ?>
                                   value="<?= $item['id'] ?>"/>
                        </label>

                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>