<div class="container text-right">
    <div class="btn-group">
        <a class="btn btn-link"
           href="<?= _url('admin.core.i18n.languages') ?>"><?= _text('Languages') ?></a>
        <a class="btn btn-link"
           href="<?= _url('admin.core.i18n.phrases') ?>"><?= _text('Translation') ?></a>
        <a class="btn btn-link"
           href="<?= _url('admin.core.i18n.add-phrase') ?>">+ <?= _text('Add') ?></a>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-admin">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Native Name</th>
            <th>Author</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($items as $item): ?>
            <tr>
                <td><?= $item['id'] ?></td>
                <td><?= $item['name'] ?></td>
                <td><?= $item['native_name'] ?></td>
                <td><?= $item['code_6391'] ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>