<div class="panel panel-default">
    <div class="table-responsive">
        <table class="table table-admin">
            <thead>
            <tr>
                <th class="w40 text-center">#</th>
                <th>ID</th>
                <th>Symbol</th>
                <th>Name</th>
                <th>Active?</th>
                <th>Default?</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($items as $item): ?>
                <tr>
                    <td class="dropdown" data-cmd="dropdown">
                        <ul>
                            <li><a data-cmd="modal" href="<?= _url('admin.core.i18n.currency',
                                    ['action' => 'edit', 'currency_id' => $item->getId()]) ?>"><?= _text('Edit') ?></li>
                        </ul>
                    </td>
                    <td><?= $item->getId() ?></td>
                    <td><?= $item->getSymbol() ?></td>
                    <td><?= $item->getName() ?></td>
                    <td>
                        <?= _yesno($item->isActive(), true, true) ?>
                    </td>
                    <td>
                        <?= _yesno($item->getId() == _param('core','currency_id'), true, false) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>