<div class="panel panel-default">
    <div class="table-responsive">
        <table class="table table-admin">
            <thead>
            <tr>
                <th class="w60 text-center">Edit</th>
                <th>Domain</th>
                <th>Language</th>
                <th>Value</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($items as $item): ?>
                <tr>
                    <td class="text-center">
                        <a data-cmd="toggle" data-rel="tr|form" role="button">edit</a>
                    </td>
                    <td><?= $item->getDomainId() ?></td>
                    <td><?= $item->getLanguageId() ? $item->getLanguageId() : '<i>n/a</i>' ?></td>
                    <td>
                        <p class="text-danger"><?= $item->getMessageName() ?></p>
                        <p class="text-value"><?= $item->getMessageValue() ?></p>
                        <form method="post" class="form hide"
                              data-submit="admin.i18n.phrase.save"
                              data-url="<?= _url(null, 'ajax/i18n/save') ?>">
                            <input type="hidden" name="domain_id"
                                   value="<?= $item->getDomainId() ?>"/>
                            <input type="hidden" name="message_name"
                                   value="<?= $item->getMessageName() ?>"/>
                            <input type="hidden" name="message_id"
                                   value="<?= $item->getId() ?>"/>
                            <div class="form-group">
                                <textarea class="form-control"
                                          name="message_value"><?= $item->getMessageValue() ?></textarea>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-sm btn-save"
                                        data-cmd="form.cmd"
                                        data-rel="save"
                                        type="button">Save
                                </button>
                                <button type="button"
                                        data-cmd="form.confirm"
                                        data-rel="delete"
                                        class="btn btn-sm btn-danger">Delete
                                </button>
                                <button class="btn btn-sm btn-cancel"
                                        type="button" data-cmd="toggle"
                                        data-rel="tr|form">Cancel
                                </button>
                            </div>
                        </form>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>