<div class="panel panel-default">
    <div class="table-responsive">
        <table class="table table-admin">
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Native Name</th>
                <th>Author</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($items as $item): ?>
                <tr>
                    <td><?= $item['id'] ?></td>
                    <td><?= $item['name'] ?></td>
                    <td><?= $item['native_name'] ?></td>
                    <td><?= $item['code_6391'] ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>