<div class="container">
    <h1>Manage Roles</h1>
    <div class="btn-group">
        <a class="btn btn-link" href="<?= _url('admin.core.authorization.add') ?>">+ <?= _text('Add Role', 'admin') ?></a>
    </div>
</div>
<div class="container">
    <div class="table-responsive">
        <table class="table table-admin">
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Inherit</th>
                <th>Option</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($items as $item): ?>
                <tr>
                    <td><?php echo $item->getId() ?></td>
                    <td><?php echo $item->getName() ?></td>
                    <td><?php echo $item->getInheritId() ?></td>
                    <td>
                        <a href="<?= _url('admin.core.authorization.edit',
                            ['id' => $item->getId()]) ?>"><?= _text('edit') ?></a>
                        &middot;
                        <a href="<?= _url('admin.core.authorization.delete',
                            ['id' => $item->getId()]) ?>"><?= _text('delete') ?></a>
                        &middot;
                        <a href="<?= _url('admin.core.authorization.settings',
                            ['id' => $item->getId()]) ?>"><?= _text('settings') ?></a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>