<div class="panel panel-default">
    <div class="table-responsive">
        <table class="table table-admin">
            <thead>
            <tr>
                <th></th>
                <th>Name</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($items as $item): ?>
                <tr>
                    <td>&nbsp;</td>
                    <td><?= $item['menu'] ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>