<?php return [
    0 => 'element_id',
    1 => ['element_id' => 1,],
    2 => 'element_id',
    3 => [
        'element_id'     => 1,
        'element_name'   => 1,
        'factory_id'     => 1,
        'is_require'     => 1,
        'label'          => 1,
        'ordering'       => 1,
        'is_active'      => 1,
        'default_value'  => 1,
        'note'           => 1,
        'has_note'       => 1,
        'note_domain'    => 1,
        'info'           => 1,
        'has_info'       => 1,
        'info_domain'    => 1,
        'text_domain'    => 1,
        'placeholder'    => 1,
        'max_length'     => 1,
        'rows'           => 1,
        'cols'           => 1,
        'is_readonly'    => 1,
        'is_disabled'    => 1,
        'class_name'     => 1,
        'is_primary'     => 1,
        'is_identity'    => 1,
        'data_cmd'       => 1,
        'meta_id'        => 1,
        'primary_length' => 1,
        'options_text'   => 1,
    ],
    4 => [],
];