<?php return [
    0 => 'meta_id',
    1 => ['meta_id' => 1,],
    2 => 'meta_id',
    3 => [
        'meta_id'      => 1,
        'package_id'   => 1,
        'table_name'   => 1,
        'action_type'  => 1,
        'action_id'    => 1,
        'text_domain'  => 1,
        'form_title'   => 1,
        'form_info'    => 1,
        'data_submit'  => 1,
        'cancel_url'   => 1,
        'action_url'   => 1,
        'title_domain' => 1,
        'info_domain'  => 1,
        'submit_label' => 1,
        'form_enctype' => 1,
        'form_method'  => 1,
    ],
    4 => [],
];