<div class="container">
    <div class="btn-group pull-right">
        <a class="btn btn-default btn-dropdown" data-toggle="dropdown" href="#">Settings</a>
        <ul class="dropdown-menu dropdown-menu-right">
            <li>
                <a href="<?= _url(':admincp', ['core/i18n/browse-phrase']) ?>">
                    Browse Phrases</a></li>
            <li>
                <a href="<?= _url(':admincp', ['core/i18n/add-phrase']) ?>">
                    Add Phrases</a></li>
            <li><a href="<?= _url(':admincp', ['core/i18n/add-phrase']) ?>">Find
                    Missing
                    Phrases</a></li>
            <li><a href="<?= _url(':admincp',
                    ['core/i18n/import-language']) ?>">
                    Import Language
                </a></li>
            <li><a href="<?= _url(':admincp',
                    ['core/i18n/import-language']) ?>">
                    Import Phrase
                </a></li>
        </ul>
    </div>
    <h1>Phrases</h1>

    <a target="_blank" class="sr-only"
       href="https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes">language
        code defined</a>
</div>
<div class="container">
    <form class="form-inline">
    <?= Phpfox::get('form.render')->render($form) ?>
    </form>
    <br/>
</div>
<div class="container">
    <table class="table table-admin">
        <tr>
            <th>Name</th>
            <th>Value</th>
            <th>Language</th>
            <th>Domain</th>
            <th>Edit</th>
        </tr>
        <?php foreach ($items as $item): ?>
            <tr>
                <td><?= $item->getName() ?></td>
                <td><?= $item->getTextValue() ?></td>
                <td><?= $item->getLanguageId() ?></td>
                <td><?= $item->getDomain() ?></td>
                <td>
                    <a href="">edit</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>