<div class="row">
    <div class="col-sm-4">
        <?= Phpfox::get('layouts')->showElement('Neutron\Core\Block\AdminUpdate'); ?>
    </div>
    <div class="col-sm-4">
        <?= Phpfox::get('layouts')->showElement('Neutron\Core\Block\AdminInformation'); ?>
    </div>
    <div class="col-sm-4">
        <?= Phpfox::get('layouts')->showElement('Neutron\Core\Block\AdminUpdate'); ?>
    </div>
</div>