<div class="panel panel-default">
    <div class="table-responsive">
        <table class="table table-admin">
            <thead>
            <tr>
                <th></th>
                <th class="text-center">#</th>
                <th>Component</th>
                <th>Active</th>
                <th>Location</th>
            </tr>
            </thead>
            <tbody class="sorted_table">
            <?php foreach ($locations as $location): ?>
                <?php foreach ($location->getElements() as $element): ?>
                    <tr>
                        <td class="draggable" title="drag to re-order" data-value="<?= $element->get('element_id') ?>"></td>
                        <td class="dropdown" data-cmd="dropdown">
                            <ul>
                                <li><a href="<?= _url('admin.core.layout.edit-element', [
                                        'id' => $element->get('element_id'),
                                    ]) ?>"><?= _text('Edit Settings') ?></a></li>
                                <li><a href="<?= _url('admin.core.layout.edit-element', [
                                        'id' => $element->get('element_id'),
                                    ]) ?>"><?= _text('Remove this block') ?></a></li>
                            </ul>
                        </td>
                        <td style="width: 70%"><?= $element->get('block_id') ?><br/>
                        <small><?= $element->get('block_class') ?></small>
                        </td>
                        <td class="w100"><?= _yesno($element->get('is_active')) ?></td>
                        <td class="w100"><?= $element->get('location_id') ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
