<div class="panel panel-default">
    <div class="table-responsive">
        <table class="table table-admin">
            <thead>
            <tr>
                <?php if (PHPFOX_IS_DEV): ?>
                    <th class="text-center">#</th>
                <?php endif; ?>
                <th>ID</th>
                <th>Name</th>
                <th>Package</th>
                <th>Active</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($items as $item): ?>
                <tr>
                    <?php if (PHPFOX_IS_DEV): ?>
                        <td class="dropdown" data-cmd="dropdown">
                            <ul>
                                <li><a href="<?= _url('admin.core.layout.action',
                                        [
                                            'action'       => 'edit-component',
                                            'component_id' => $item->getId(),
                                        ]) ?>"><?= _text('Edit Component') ?></a></li>
                            </ul>
                        </td>
                    <?php endif; ?>
                    <td>
                        <?= $item->getId() ?>
                    </td>
                    <td><?= $item->__get('component_name') ?><br/>
                    <small><?= $item->__get('description') ?></small></td>
                    <td><?= $item->__get('package_id') ?></td>
                    <td><?= _yesno($item->isActive()) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>