<div class="panel panel-default">
    <div class="table-responsive">
        <table class="table table-admin">
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Class</th>
                <th>Package</th>
                <th>Desc.</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($items as $item): ?>
                <tr>
                    <td>
                        <a href="<?= _url('admin.core.layout.edit-component',
                            ['component_id' => $item->getId()]) ?>"><?= $item->getId() ?></a>
                    </td>
                    <td><?= $item->__get('component_name') ?></td>
                    <td><?= $item->__get('component_class') ?></td>
                    <td><?= $item->__get('package_id') ?></td>
                    <td><?= $item->__get('description') ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>