<?php return [
    0 => 'id',
    1 => ['id' => 1,],
    2 => 'id',
    3 => [
        'id'          => 1,
        'category_id' => 1,
        'poster_id'   => 1,
        'user_id'     => 1,
        'parent_id'   => 1,
        'poster_type' => 1,
        'parent_type' => 1,
        'created_at'  => 1,
        'updated_at'  => 1,
        'title'       => 1,
        'description' => 1,
        'content'     => 1,
    ],
    4 => [],
];