<?php echo '<?php' ?>

namespace <?= $namespace ?>;

use Phpfox\Form\Form;

class <?= $shortFormClass?> extends Form {

    public function initialize(){

        $this->setTitle(_text('<?= $formTitle ?>', '<?= $titleDomain ?>'));
        $this->setInfo(_text('<?= $formInfo ?>', '<?= $infoDomain?>'));
        <?php if($formMethod):?>$this->setMethod('<?= $formMethod ?>'); <?php endif;?>
        <?php if($formEncType):?>$this->setEncType('<?= $encType ?>'); <?php endif;?>
        $this->setAction(_url('#'));

        /** start elements **/

        <?php foreach($elements as $element): ?>

        <?php echo $elementGenerator->convert($element); ?>
        <?php endforeach; ?>

        /** end elements **/

        $this->addButton([
            'factory'    => 'button',
            'name'       => 'save',
            'label'      => _text('<?= $submitLabel?$submitLabel: 'Save Changes'?>'),
            'attributes' => ['class' => 'btn btn-primary','type' => 'submit',],
        ]);

        $this->addButton([
            'factory'    => 'button',
            'name'       => 'cancel',
            'href'       => _url('<?= $cancelUrl ?>'),
            'label'      => _text('Cancel'),
            'attributes' => ['class' => 'btn btn-link cancel','type'=>'button','data-cmd' => 'form.cancel',],
        ]);
    }
}
