<div class="container">
    <?php foreach ($items as $item): ?>
        <div class="row">
            <div class="col-xs-3"><?= _text('Device', 'login history') ?></div>
            <div class="col-xs-9"><?= $item->getDeviceName() ?></div>
        </div>
        <div class="row">
            <div class="col-xs-3"><?= _text('Login IP', 'login history') ?></div>
            <div class="col-xs-9"><?= $item->getRemoteAddress() ?></div>
        </div>
        <div class="row">
            <div class="col-xs-3"><?= _text('Last Login', 'login history') ?></div>
            <div class="col-xs-9"><?= $item->getCreatedAt() ?></div>
        </div>
        <hr/>
    <?php endforeach; ?>
</div>