<div class="panel panel-default">
    <div class="table-responsive">
        <table class="table table-admin">
            <thead>
            <tr>
                <th class="text-center w40">#</th>
                <th><?= _text('Title') ?></th>
                <th class="w100"><?= _text('Driver') ?></th>
                <th class="w50"><?= _text('Default') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($items as $item): ?>
                <tr>
                    <td class="dropdown" data-cmd="dropdown">
                        <ul role="menu">
                            <li role="menuitem"><a data-cmd="modal" href="<?= _url('admin.core.captcha',
                                    ['action' => 'default', 'adapter_id' => $item->getId()]) ?>">
                                    <?= _text('Set Default') ?>
                                </a></li>
                            <li role="menuitem"><a data-cmd="modal" data-size="md" href="<?= _url('admin.core.captcha',
                                    ['action' => 'edit', 'adapter_id' => $item->getId()]) ?>">
                                    <?= _text('Edit Settings') ?>
                                </a></li>
                            <?php if (!$item->isRequired()): ?>
                                <li class="divider"></li>
                                <li role="menuitem"><a data-cmd="modal" href="<?= _url('admin.core.captcha',
                                        ['action' => 'delete', 'adapter_id' => $item->getId()]) ?>">
                                        <?= _text('Delete') ?>
                                    </a></li>
                            <?php endif; ?>
                        </ul>
                    </td>
                    <td><?= $item->getTitle() ?></td>
                    <td><?= $item->getDriverId() ?></td>
                    <td><?= _yesno($item->isDefault(), true, false) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>