<div class="container">
    <h2><?= $heading ?></h2>
    <?php echo $form->open(); ?>
    <?php echo _get('form_render')->render($form); ?>
    <div class="form-group">
        <button class="btn btn-primary" type="submit"
                name="_submit"><?= _text('Send') ?></button>
        <a href=".." class="btn btn-link"><?= _text('Cancel') ?></a>
    </div>
    <?php echo $form->close(); ?>
</div>