<!DOCTYPE html>
<html>
<head>
    <?= _get('assets')->getStartHtml() ?>
</head>
<body class="<?= PHPFOX_IS_DEV ? 'is_dev' : '' ?>">
<header>

    <?php $login = _get('auth')->getLogin(); ?>
    <div class="navbar">
        <?= _get('breadcrumb')->render() ?>
        <form role="search" class="navbar-form navbar-right global-search-holder"
              onsubmit="return false;">
            <input type="text" placeholder="<?= _text('Search ...') ?>"
                   class="form-control">
        </form>
    </div>
</header>
<div class="top-left">
</div>
<aside>
    <div class="top">PHPFOX</div>
    <?= _get('menu.admin.primary')->render('aside', []) ?>
    <ul>
        <li><a role="button">logged as <?= $login->getName() ?></a></li>
        <li><a href="<?= _url('logout') ?>"><?= _text('Logout') ?></a></li>
    </ul>
</aside>
<section class="main-wrapper">
    <div class="container">
        <?= _get('menu.admin.secondary')->render('toolbar', ['level0' => 'btn-group toolbar pull-left']); ?>
        <?= _get('menu.admin.buttons')->render('toolbar', ['level0' => 'btn-group toolbar pull-right']); ?>
    </div>
    <div class="container">
        <?= _get('layouts')->renderBlock('\Neutron\Core\Block\AdminFilter', []) ?>
    </div>
    <div class="content-wrapper">
        <?php echo @$layout_content ?>
    </div>
</section>
<?= _get('assets')->getShutdownHtml() ?>
</body>
</html>