<!DOCTYPE html>
<html>
<head>
    <?= _get('assets')->getStartHtml() ?>
</head>
<body class="admin-login">
<section>
    <div class="login">
        <form method="post">
            <input type="hidden" name="is_login" value="1" />
            <h1>Admin</h1>
            <?php if (!empty($message)): ?><p
                    class="text-danger"><?= $message ?></p><?php endif; ?>
            <div class="form-group">
                <input type="text" name="email" class="form-control" placeholder="Email address" autocomplete="on" spellcheck="false" autofocus required maxlength="255"/>
            </div>
            <div class="form-group form-large">
                <input type="password" name="password" class="form-control"
                       placeholder="Password" required maxlength="32"/>
            </div>
            <button class="btn btn-danger btn-block" type="submit">Log In
            </button>
            <figure>
                <a class="btn btn-link" href="#">Go back</a>
            </figure>
        </form>
    </div>
</section>
<?= _get('assets')->getShutdownHtml() ?>
</body>
</html>