<?php echo '<?php' ?>

namespace <?= $namespace ?>;

class <?= $modelName ?>Test extends \PHPUnit_Framework_TestCase
{
    public function testBase()
    {
        $obj = new <?= $modelName ?>(<?= $initialData ?>);

        <?= $assertSameMethod ?>
    }

    public function testParameters()
    {
        $obj = new <?= $modelName ?>();

        // set data
        <?= $setDataMethods ?>

        // assert same data
        <?= $assertSameMethod ?>
    }

    public function testSave()
    {
        $obj = new <?= $modelName ?>(<?= $initialData ?>);

        $obj->save();

        /** @var <?= $modelName ?> $obj */
        $obj = \Phpfox::model('<?= $modelId ?>')
            ->select()<?= $whereConditions ?>->first();

        <?= $assertSameMethod ?>
    }

    public static function setUpBeforeClass()
    {
        \Phpfox::model('<?= $modelId ?>')
            ->delete()<?= $whereConditions ?>->execute();
    }

    public static function tearDownAfterClass()
    {
        \Phpfox::model('<?= $modelId ?>')
            ->delete()<?= $whereConditions ?>->execute();
    }
}