<div class="container">
    <div class="row">
        <h1>Packages
            <div class="pull-right">
                <div class="btn-group">
                    <a class="btn btn-link" href="<?= _url('admin.core.package.apps')?>">Apps</a>
                    <a class="btn btn-link" href="<?= _url('admin.core.package.themes')?>">Themes</a>
                    <a class="btn btn-link" href="<?= _url('admin.core.package.languages')?>">Languages</a>
                    <a class="btn btn-link" href="<?= _url('admin.core.package.libraries')?>">Libraries</a>
                    <a class="btn btn-link" href="<?= _url('admin.core.package.add')?>"> + Upload</a>
                </div>
            </div>
        </h1>
        <div class="table-responsive">
            <table class="table table-admin">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Version</th>
                    <th>Author</th>
                    <th>Active</th>
                </tr>
                <?php foreach ($items as $item): ?>
                    <tr>
                        <td><?= $item['id'] ?></td>
                        <td><?= $item['var_name'] ?></td>
                        <td><?= $item['version'] ?></td>
                        <td><?= $item['author'] ?></td>
                        <td>
                            <label for="_">
                                <input name="item[active][]" id="_"
                                       type="checkbox" <?= $item['is_active']
                                    ? 'checked' : '' ?>
                                       value="<?= $item['id'] ?>"/>
                            </label>

                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>