<?php if (!empty($items)): ?>
    <div class="container">
        Select one of following driver

        <?php foreach ($items as $item): ?>
            <h5><?= $item->getTitle() ?></h5>
            <p class="help-block"><?= $item->getDescription() ?></p>
            <p>
                <a href="?driver_name=<?= $item->getId() ?>"
                   class="btn btn-info">Continue</a>
            </p>
            <hr/>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <div class="container">
        <?php echo $form->open(); ?>
        <?php echo Phpfox::get('form.render')->render($form); ?>
        <div class="form-group">
            <button class="btn btn-primary" type="submit"
                    name="_submit"><?= _text('Save Changes') ?></button>
            <a href=".." class="btn btn-link"><?= _text('Cancel') ?></a>
        </div>
        <?php echo $form->close(); ?>
    </div>
<?php endif; ?>