<div class="panel panel-default">
    <div class="table-responsive">
        <table class="table table-admin">
            <tr>
                <th class="text-center">#</th>
                <th>ID</th>
                <th>Name</th>
                <th>Driver ID</th>
                <th>Active?</th>
                <th>Default</th>
                <th>Required</th>
            </tr>
            <?php foreach ($items as $item): ?>
                <tr>
                    <td class="dropdown" data-cmd="dropdown">
                        <ul>
                            <li><a href="<?= _url('admin.core.mail.adapter',
                                    ['action'=>'edit','adapter_id' => $item->getId()]) ?>"><?= _text('Edit Settings') ?></a></li>
                            <li><a href="<?= _url('admin.core.mail.adapter',
                                    ['action'=>'default','adapter_id' => $item->getId()]) ?>"><?= _text('Set Default') ?></a></li>
                            <li><a data-cmd="modal" href="<?= _url('admin.core.mail.adapter',
                                    ['action'=>'test','adapter_id' => $item->getId()]) ?>"><?= _text('Send Test Email') ?></a></li>
                        </ul>
                    </td>
                    <td><?= $item->getId() ?></td>
                    <td><?= $item->getAdapterName() ?></td>
                    <td><?= $item->getDriverId() ?></td>
                    <td><?= _yesno($item->isActive(), true, false) ?></td>
                    <td><?= _yesno($item->getId() == $defaultValue, true, false) ?></td>
                    <td><?= _yesno($item->isRequired(), true, false) ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>