<div class="panel panel-default">
    <div class="table-responsive">
        <table class="table table-admin">
            <thead>
            <tr>
                <th class="text-center w40">#</th>
                <th class="w100">Driver Id</th>
                <th class="w200">Name</th>
                <th class="">Description</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($items as $item): ?>
                <tr>
                    <td class="dropdown" data-cmd="dropdown">

                        <ul role="menu">

                            <li role="menuitem"><a href="<?= _url('admin.core.mail.driver',
                                    ['action' => 'edit', 'driver_id' => $item->getId()]) ?>">
                                    <?= _text('Edit') ?>
                                </a></li>
                            <li role="menuitem">
                                <a href="<?= _url('admin.core.mail.adapter',
                                    ['action' => 'config', 'driver_id' => $item->getId()]) ?>">
                                    <?= _text('Add New Adapter', 'admin.core_mail') ?>
                                </a></li>
                        </ul>
                    </td>
                    <td><?= $item->getId() ?></td>
                    <td><?= $item->getDriverName() ?></td>
                    <td><?= $item->getDescription() ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>