<div class="panel panel-default">
    <div class="table-responsive">
        <table class="table table-admin">
            <tr>
                <th class="text-center">#</th>
                <th>ID</th>
                <th>Name</th>
                <th>Driver ID</th>
                <th>Default?</th>
            </tr>
            <?php foreach ($items as $item): ?>
                <tr>
                    <td class="dropdown" data-cmd="dropdown">
                        <ul>
                            <li><a href="<?= _url('admin.core.mail.edit-adapter',['id'=>$item->getId()]) ?>"><?= _text('Edit Settings') ?></a></li>
                            <li><a href="<?= _url('admin.core.mail.edit-adapter',['id'=>$item->getId()]) ?>"><?= _text('Set Default') ?></a></li>
                            <li><a href="<?= _url('admin.core.mail.test-adapter',['id'=>$item->getId()]) ?>"><?= _text('Send Test Email') ?></a></li>
                        </ul>
                    </td>
                    <td><?= $item->getId() ?></td>
                    <td><?= $item->getTitle() ?></td>
                    <td><?= $item->getDriverId() ?></td>
                    <td><?= _yesno($item->isDefault(),true,false) ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>