<?= $this->render('core/admin-mail/menu', []) ?>

<div class="container">
    <div class="table-responsive">
        <table class="table table-admin">
            <thead>
            <tr>
                <th class="fit">ID</th>
                <th>Name</th>
                <th>Driver</th>
                <th>Default?</th>
                <th>Option</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($items as $item): ?>
                <tr>
                    <td><?= $item->getId() ?></td>
                    <td><?= $item->getName() ?></td>
                    <td><?= $item->getDriver() ?></td>
                    <td><?= _yesno($item->isDefault()) ?></td>
                    <td class="cmds">
                        <a href="<?= _url('admin') ?>"><?= _text('edit') ?></a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>

        </table>
    </div>
</div>