<div class="panel panel-info">
    <div class="panel-body">
        <?= $message ?>
    </div>
</div>
<div class="panel">
    <div class="table-responsive">
        <table class="table table-admin">
            <tr>
                <th class="text-center">#</th>
                <th>Info.</th>
                <th class="w80">Version</th>
                <th class="w80" data-toggle="tooltip">Required</th>
                <th class="w80">Type</th>
                <th class="w80">Author</th>
                <th class="w80">Active</th>
            </tr>
            <?php foreach ($items as $item): ?>
                <tr>
                    <td data-cmd="dropdown" class="dropdown">
                        <ul role="menu">
                            <?php if ($item->canDisable()): ?>
                                <li role="menuitem">
                                    <a href="<?= _url('admin.core.package',
                                        ['action' => 'disable', 'package_id' => $item->getId()]) ?>">Disable</a></li>
                            <?php elseif ($item->canEnable()): ?>
                                <li role="menuitem">
                                    <a href="<?= _url('admin.core.package',
                                        ['action' => 'enable', 'package_id' => $item->getId()]) ?>">Enable</a></li>
                            <?php endif; ?>
                            <?php if ($item->canExport()): ?>
                                <li role="menuitem">
                                    <a href="<?= _url('admin.core.package',
                                        ['action' => 'export', 'package_id' => $item->getId()]) ?>">Export</a></li>
                            <?php endif; ?>
                            <?php if ($item->canUpgrade()): ?>
                                <li role="menuitem">
                                    <a href="<?= _url('admin.core.package',
                                        ['action' => 'upgrade', 'package_id' => $item->getId()]) ?>">Upgrade</a></li>
                            <?php endif; ?>
                            <?php if ($item->canUninstall()): ?>
                                <li role="menuitem">
                                    <a href="<?= _url('admin.core.package',
                                        ['action' => 'delete', 'package_id' => $item->getId()]) ?>">Uninstall</a></li>
                            <?php endif; ?>
                        </ul>
                    </td>
                    <td><?= $item->getTitle() ?></td>
                    <td><?= $item['version'] ?></td>
                    <td>
                        <?php if ($item->isRequired()): ?>
                            <label class="label label-success"><?= _text('Yes') ?></label>
                        <?php else: ?>
                            <?= _text('No') ?>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?= $item->getTypeId() ?>
                    </td>
                    <td><?= $item['author'] ?></td>
                    <td>
                        <?php if ($item->isActive()): ?>
                            <?= _text('Yes') ?>
                        <?php else: ?>
                            <label class="label label-danger"><?= _text('No') ?></label>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>
<?= $items->render(); ?>