<!DOCTYPE html>
<html>
<head>
    <?= \Phpfox::get('assets')->getStartHtml() ?>
</head>
<body class="">
<header>
    <?= $this->render('layout/header', []) ?>
</header>
<div id="layout_containers">
    <section id="content">
        <?php echo @$layout_content ?>
    </section>
</div>
<footer>
    <?= $this->render('layout/footer', []) ?>
</footer>
<?= \Phpfox::get('assets')->getShutdownHtml() ?>
</body>
</html>