<?php return [
    0 => 'user_id',
    1 => ['user_id' => 1,],
    2 => 'user_id',
    3 => [
        'user_id'       => 1,
        'level_id'      => 1,
        'user_photo_id' => 1,
        'gender_id'     => 1,
        'status_id'     => 1,
        'view_id'       => 1,
        'username'      => 1,
        'fullname'      => 1,
        'email'         => 1,
        'locale_id'     => 1,
        'timezone'      => 1,
        'created_at'    => 1,
    ],
    4 => [],
];