<div class="table-responsive">
    <table class="table table-admin">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Version</th>
            <th>Author</th>
            <th>Default?</th>
            <th>Action</th>
        </tr>
        <?php foreach ($items as $item): ?>
            <tr>
                <td>
                    <?= $item->getId() ?>
                </td>
                <td><a href="<?= _url('admin.core.theme.edit',
                        ['id' => $item->getId()]) ?>"><?= $item->getName() ?></a>
                </td>
                <td><?= $item['version'] ?></td>
                <td><?= $item['author'] ?></td>
                <td>
                    <?= _yesno($item->isDefault()) ?>
                </td>
                <td class="cmds">
                    <?php if (!$item->isDefault()): ?>
                        <a href="<?= _url('admin.core.theme', null, [
                            'cmd' => 'default',
                            'id'  => $item->getId(),
                        ]) ?>" role="button"
                           class=""><?= _text('Default') ?></a>
                    <?php endif; ?>
                    <a href="<?= _url('admin.core.theme', null, [
                        'cmd' => 'rebuild-main',
                        'id'  => $item->getId(),
                    ]) ?>" role="button"
                       class=""><?= _text('Rebuild Main',
                            'admin') ?></a>
                    <a href="<?= _url('admin.core.theme', null, [
                        'cmd' => 'rebuild-files',
                        'id'  => $item->getId(),
                    ]) ?>" role="button"
                       class=""><?= _text('Rebuild Files',
                            'admin') ?></a>
                    <a href="<?= _url('admin.core.theme.debug',
                        ['id' => $item->getId()]) ?>" role="button"
                       class=""><?= _text('Debug', 'admin') ?></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>