<!DOCTYPE html>
<html>
<head>
    <?= \Phpfox::get('assets')->getStartHtml() ?>
</head>
<body class="<?= PHPFOX_IS_DEV ? 'is_dev' : '' ?>">

<aside>
    <div>
        <?= \Phpfox::get('menu.admin.primary')->render('aside', []) ?>
    </div>
    <div>
        <ul>
            <li><a class="no-ajax"
                   href="<?= _url('admin.core.auth', ['action' => 'logout']) ?>"><?= _text('Logout') ?></a></li>
        </ul>
    </div>
</aside>
<div id="layout_containers">
    <header>
        <div class="left">
            <a role="button" class="aside-toggle" data-cmd="toggle" data-target="//body;aside-closed">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a role="link" class="brand" href="#">PHPFOX</a>
        </div>
        <div class="main">
            <div class="navbar">
                <?= \Phpfox::get('breadcrumb')->render() ?>
                <form role="search" class="navbar-form navbar-right global-search-holder"
                      onsubmit="return false;">
                    <input type="text" placeholder="<?= _text('Search ...') ?>"
                           class="form-control">
                </form>
            </div>
        </div>
    </header>
    <div class="main-wrapper">
        <div class="container">
            <?= \Phpfox::get('menu.admin.secondary')->render('toolbar', ['level0' => 'btn-group toolbar pull-left']); ?>
            <?= \Phpfox::get('menu.admin.buttons')->render('toolbar', ['level0' => 'toolbar pull-right']); ?>
        </div>
        <div class="container">
            <?= \Phpfox::get('layouts')->renderBlock('\Neutron\Core\Block\AdminFilter', []) ?>
        </div>
        <div class="content-wrapper">
            <?php echo @$layout_content ?>
        </div>
    </div>
</div>
<?= \Phpfox::get('assets')->getShutdownHtml() ?>
</body>
</html>