<div class="panel panel-default">
    <div class="table-responsive">
        <table class="table table-admin">
            <thead>
            <tr>
                <th class="w40 text-center">#</th>
                <th>ID</th>
                <th>Name</th>
                <th>Inherit</th>
                <th>Pages</th>
                <th>Required?</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($items as $item): ?>
                <tr>
                    <td class="dropdown" data-cmd="dropdown">
                        <ul>
                            <li><a href="<?= _url('admin.pages.level',
                                    ['action' => 'edit', 'level_id' => $item->getId()]) ?>">
                                    <?= _text('Edit Level') ?></a></li>
                            <div class="divider"></div>
                            <li><a href="<?= _url('admin.pages.level',
                                    ['action' => 'delete', 'level_id' => $item->getId()]) ?>">
                                    <?= _text('Delete Level') ?></a></li>

                        </ul>
                    </td>
                    <td><?php echo $item->getId() ?></td>
                    <td><?php echo $item->getTitle() ?></td>
                    <td><?php echo $item->getInheritId() ?></td>
                    <td><?php echo $item->getItemCount() ?></td>
                    <td><?= _yesno($item->isCore()) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>