<?php return [
    0 => 'event_id',
    1 => ['event_id' => 1,],
    2 => 'event_id',
    3 => [
        'event_id' => 1,
        'is_featured' => 1,
        'is_sponsor' => 1,
        'privacy_id' => 1,
        'parent_id' => 1,
        'poster_id' => 1,
        'user_id' => 1,
        'location_id' => 1,
        'photo_id' => 1,
        'start_at' => 1,
        'end_at' => 1,
        'created_at' => 1,
        'title' => 1,
        'poster_type' => 1,
        'parent_type' => 1,
    ],
    4 => [],
];