<li class="layout-editor-block">
    <i class="fa fa-ellipsis-v" style="margin-left: -5px;font-size:smaller"></i>
    <?= $block->get('block_name') ?>
    <span data-cmd="dropdown" role="button" style="float:right" data-target=":li/ul">
        <small>edit</small>
    </span>
    <div class="hide">
        <ul>
            <li>
                <a role="button">Edit Settings</a>
            </li>
            <li class="divider"></li>
            <li>
                <a role="button">Enable</a>
            </li>
            <li>
                <a role="button">Disable</a>
            </li>
            <li class="divider"></li>
            <li>
                <a role="button">Remove</a>
            </li>
        </ul>
    </div>
</li>