<li class="layout-editor-block">
    <?= $block->get('block_name') ?>
    <span data-cmd="dropdown" role="button" style="float:right">
        <small>Edit</small>
        <ul class="dropdown-menu dropdown-menu-right">
            <li>
                <a role="button">Edit Settings</a>
            </li>
            <li class="divider"></li>
            <li>
                <a role="button">Enable</a>
            </li>
            <li>
                <a role="button">Disable</a>
            </li>
            <li class="divider"></li>
            <li>
                <a role="button">Remove</a>
            </li>
        </ul>
    </span>
</li>