<div class="panel panel-default">
    <div class="panel-heading">
        <div class="pull-right">
            <button class="btn btn-xs btn-info">Edit</button>
            <button class="btn btn-xs btn-info">Remove</button>
            <button class="btn btn-xs btn-info">Toggle</button>
        </div>
        <div class="panel-title">Container <?= $container->getName() ?></div>
    </div>
    <?= $content ?>
</div>