<div class="layout-location-heading">
    <strong><?= $location['location_id'] ?></strong>
    <span data-cmd="dropdown" role="button" style="float:right" data-target=":div/ul">
        <small>edit</small>
    </span>
    <ul class="hide" role="menu">
        <li role="menuitem">
            <a data-cmd="modal" href="<?= _url('admin.core.layout.action',
                ['action' => 'add-block', 'location_id' => $location['location_id'],'container'=>$location['container_id']]) ?>">Add Block</a>
        </li>
        <li role="menuitem">
            <a role="button">Edit Settings</a>
        </li>
        <li class="divider"></li>
        <li role="menuitem">
            <a>Enable all block</a>
        </li>
        <li role="menuitem">
            <a role="button">Disable all block</a>
        </li>
    </ul>
</div>
<ul class="layout-editor-location">
    <?php foreach($blocks as $block): ?>
        <li class="layout-editor-block">
            <i class="fa fa-ellipsis-v" style="margin-left: -5px;font-size:smaller"></i>
            <?= $block['block_name'] ?>
            <span data-cmd="dropdown" role="button" style="float:right" data-target=":li/ul">
                <small>edit</small>
            </span>
            <div class="hide">
                <ul>
                    <li>
                        <a role="button">Edit Settings</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a role="button">Enable</a>
                    </li>
                    <li>
                        <a role="button">Disable</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a role="button">Remove</a>
                    </li>
                </ul>
            </div>
        </li>
    <?php endforeach; ?>
</ul>