<?php return [
    0 => 'page_id',
    1 => ['page_id' => 1,],
    2 => 'page_id',
    3 => [
        'page_id'        => 1,
        'is_featured'    => 1,
        'is_sponsor'     => 1,
        'type_id'        => 1,
        'category_id'    => 1,
        'user_id'        => 1,
        'profile_name'   => 1,
        'title'          => 1,
        'photo_id'       => 1,
        'cover_photo_id' => 1,
        'like_count'     => 1,
        'comment_count'  => 1,
        'created_at'     => 1,
    ],
    4 => [],
];