<!DOCTYPE html>
<html>
<head>
    <?= Phpfox::get('assets')->getStartHtml() ?>
</head>
<body class="">
<header>
    <?= $this->render('layout/header', []) ?>
</header>
<section id="content">
    <div class="container">
        <?php echo @$layout_content ?>
    </div>
</section>
<footer>
    <?= $this->render('layout/footer', []) ?>
</footer>
<?= Phpfox::get('assets')->getShutdownHtml() ?>
</body>
</html>