<?php $login = Phpfox::get('auth')->getLogin(); ?>
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="collapsed navbar-toggle"
                    data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1"
                    aria-expanded="false"><span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span> <span class="icon-bar"></span>
                <span class="icon-bar"></span></button>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <?= \Phpfox::get('navigation')->render('navbar', 'main') ?>
            <?= \Phpfox::get('navigation')
                ->render('navbar', 'main.mini', null, null, 3,
                    ['level0' => 'nav navbar-nav navbar-right']) ?>
        </div>
    </div>
</nav>