<?php return [
    0 => 'group_id',
    1 => ['group_id' => 1,],
    2 => 'group_id',
    3 => [
        'group_id'     => 1,
        'user_id'      => 1,
        'title'        => 1,
        'description'  => 1,
        'category_id'  => 1,
        'location_id'  => 1,
        'invite_id'    => 1,
        'is_approval'  => 1,
        'is_featured'  => 1,
        'parent_id'    => 1,
        'parent_type'  => 1,
        'photo_id'     => 1,
        'cover_id'     => 1,
        'created_at'   => 1,
        'updated_at'   => 1,
        'member_count' => 1,
        'view_count'   => 1,
        'poster_id'    => 1,
        'poster_type'  => 1,
    ],
    4 => [],
];