<form method="post">
    <div class="panel panel-default">
        <div class="table table-responsive">
            <table class="table table-admin">
                <thead>
                <tr>
                    <th class="w30">
                        <label><input type="checkbox" class="moderation-check-all"/></label>
                    </th>
                    <th>Table</th>
                    <th>Admin Add</th>
                    <th>Admin Edit</th>
                    <th>Admin Delete</th>
                    <th>Admin Filter</th>
                    <th>Model Class</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($items as $item): ?>
                    <tr>
                        <td>
                            <label><input id="cb" type="checkbox" name="tables[]" value="<?= $item->getId() ?>"
                                          class="item_checkbox"/></label>
                        </td>
                        <td>
                            <?= $item->getId(); ?>
                        </td>
                        <td>
                            <?= $item->toFormControl('admin_add') ?>
                        </td>
                        <td>
                            <?= $item->toFormControl('admin_edit') ?>
                        </td>
                        <td>
                            <?= $item->toFormControl('admin_delete') ?>
                        </td>
                        <td>
                            <?= $item->toFormControl('admin_filter') ?>
                        </td>
                        <td>
                            <?= $item->toFormControl('model_class') ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <div class="panel-footer">
            <button class="btn btn-primary" name="cmd" type="submit" value="save">Saves</button>
            <button class="btn btn-primary" name="cmd" type="submit" value="process">Process</button>
        </div>
    </div>
</form>