
<form method="post">
    <div class="panel panel-default">
        <div class="table table-responsive">
            <table class="table table-bordered table-hover table-striped">
                <thead>
                <tr>
                    <th class="w30">
                        <label><input type="checkbox" class="moderation-check-all"/></label>
                    </th>
                    <th>ID</th>
                    <th>Action</th>
                    <th>Options</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($items as $item): ?>
                    <tr>

                        <td>
                            <label><input id="cb" type="checkbox" name="selected[]" <?= in_array($item->getId(),$selected)?'checked':'' ?> value="<?= $item->getId() ?>"
                                          class="item_checkbox"/></label>
                        </td>
                        <td>
                            <?= $item->getId() ?>
                        </td>
                        <td>
                            <?= $item->getActionName(); ?>
                        </td>
                        <td>
                            <?= $item->toFormControl('admin_add') ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <div class="panel-footer">
            <button class="btn btn-primary" name="cmd" type="submit" value="save">Process</button>
        </div>
    </div>
</form>