<div class="panel panel-default">
    <div class="table-responsive">
        <table class="table table-admin">
            <thead>
            <tr>
                <th class="w40 text-center">#</th>
                <th class="w40">ID</th>
                <th class="w100">Inherit ID</th>
                <th class="w100">Total User</th>
                <th class="w100">Required?</th>
                <th>Name</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($items as $item): ?>
                <tr>
                    <td class="dropdown" data-cmd="dropdown">
                        <ul>
                            <li><a href="<?= _url('admin.user.level',
                                    ['action' => 'edit', 'level_id' => $item->getId()]) ?>">
                                    <?= _text('Edit Level','admin') ?></a></li>
                            <div class="divider"></div>
                            <li><a href="<?= _url('admin.user.level',
                                    ['action' => 'delete', 'level_id' => $item->getId()]) ?>">
                                    <?= _text('Delete Level','admin') ?></a></li>

                        </ul>
                    </td>
                    <td class="w40"><?php echo $item->getId() ?></td>
                    <td class="w100"><?php echo $item->getInheritId() ?></td>
                    <td class="w100"><?php echo _number($item->getItemCount()) ?></td>
                    <td class="w100"><?= _yesno($item->isCore()) ?></td>
                    <td><?php echo $item->getTitle() ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>